<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.11.2" name="textures_2" tilewidth="64" tileheight="64" tilecount="400" columns="25">
 <image source="textures_2.png" width="1600" height="1024"/>
 <tile id="0" type="tank"/>
 <tile id="1" type="tank"/>
 <tile id="2" type="tank"/>
 <tile id="3" type="tank"/>
 <tile id="4" type="tank"/>
 <tile id="5" type="tank"/>
 <tile id="6" type="tank"/>
 <tile id="7" type="tank"/>
 <tile id="8" type="tank"/>
 <tile id="9" type="tank"/>
 <tile id="10" type="tank"/>
 <tile id="11" type="tank"/>
 <tile id="12" type="tank"/>
 <tile id="13" type="tank"/>
 <tile id="14" type="tank"/>
 <tile id="15" type="tank"/>
 <tile id="16" type="1"/>
 <tile id="17" type="1"/>
 <tile id="18" type="1"/>
 <tile id="19" type="1"/>
 <tile id="20" type="1"/>
 <tile id="25" type="tank"/>
 <tile id="26" type="tank"/>
 <tile id="27" type="tank"/>
 <tile id="28" type="tank"/>
 <tile id="29" type="tank"/>
 <tile id="30" type="tank"/>
 <tile id="31" type="tank"/>
 <tile id="32" type="tank"/>
 <tile id="33" type="tank"/>
 <tile id="34" type="tank"/>
 <tile id="35" type="tank"/>
 <tile id="36" type="tank"/>
 <tile id="37" type="tank"/>
 <tile id="38" type="tank"/>
 <tile id="39" type="tank"/>
 <tile id="40" type="tank"/>
 <tile id="41" type="2"/>
 <tile id="42" type="2"/>
 <tile id="43" type="2"/>
 <tile id="44" type="2"/>
 <tile id="45" type="2"/>
 <tile id="50" type="tank"/>
 <tile id="51" type="tank"/>
 <tile id="52" type="tank"/>
 <tile id="53" type="tank"/>
 <tile id="54" type="tank"/>
 <tile id="55" type="tank"/>
 <tile id="56" type="tank"/>
 <tile id="57" type="tank"/>
 <tile id="58" type="tank"/>
 <tile id="59" type="tank"/>
 <tile id="60" type="tank"/>
 <tile id="61" type="tank"/>
 <tile id="62" type="tank"/>
 <tile id="63" type="tank"/>
 <tile id="64" type="tank"/>
 <tile id="65" type="tank"/>
 <tile id="66" type="3"/>
 <tile id="67" type="5"/>
 <tile id="68" type="7"/>
 <tile id="69" type="4"/>
 <tile id="75" type="tank"/>
 <tile id="76" type="tank"/>
 <tile id="77" type="tank"/>
 <tile id="78" type="tank"/>
 <tile id="79" type="tank"/>
 <tile id="80" type="tank"/>
 <tile id="81" type="tank"/>
 <tile id="82" type="tank"/>
 <tile id="83" type="tank"/>
 <tile id="84" type="tank"/>
 <tile id="85" type="tank"/>
 <tile id="86" type="tank"/>
 <tile id="87" type="tank"/>
 <tile id="88" type="tank"/>
 <tile id="89" type="tank"/>
 <tile id="90" type="tank"/>
 <tile id="91" type="3"/>
 <tile id="92" type="3"/>
 <tile id="100" type="tank"/>
 <tile id="101" type="tank"/>
 <tile id="102" type="tank"/>
 <tile id="103" type="tank"/>
 <tile id="104" type="tank"/>
 <tile id="105" type="tank"/>
 <tile id="106" type="tank"/>
 <tile id="107" type="tank"/>
 <tile id="108" type="tank"/>
 <tile id="109" type="tank"/>
 <tile id="110" type="tank"/>
 <tile id="111" type="tank"/>
 <tile id="112" type="tank"/>
 <tile id="113" type="tank"/>
 <tile id="114" type="tank"/>
 <tile id="115" type="tank"/>
 <tile id="125" type="tank"/>
 <tile id="126" type="tank"/>
 <tile id="127" type="tank"/>
 <tile id="128" type="tank"/>
 <tile id="129" type="tank"/>
 <tile id="130" type="tank"/>
 <tile id="131" type="tank"/>
 <tile id="132" type="tank"/>
 <tile id="133" type="tank"/>
 <tile id="134" type="tank"/>
 <tile id="135" type="tank"/>
 <tile id="136" type="tank"/>
 <tile id="137" type="tank"/>
 <tile id="138" type="tank"/>
 <tile id="139" type="tank"/>
 <tile id="140" type="tank"/>
 <tile id="150" type="tank"/>
 <tile id="151" type="tank"/>
 <tile id="152" type="tank"/>
 <tile id="153" type="tank"/>
 <tile id="154" type="tank"/>
 <tile id="155" type="tank"/>
 <tile id="156" type="tank"/>
 <tile id="157" type="tank"/>
 <tile id="158" type="tank"/>
 <tile id="159" type="tank"/>
 <tile id="160" type="tank"/>
 <tile id="161" type="tank"/>
 <tile id="162" type="tank"/>
 <tile id="163" type="tank"/>
 <tile id="164" type="tank"/>
 <tile id="165" type="tank"/>
 <tile id="175" type="tank"/>
 <tile id="176" type="tank"/>
 <tile id="177" type="tank"/>
 <tile id="178" type="tank"/>
 <tile id="179" type="tank"/>
 <tile id="180" type="tank"/>
 <tile id="181" type="tank"/>
 <tile id="182" type="tank"/>
 <tile id="183" type="tank"/>
 <tile id="184" type="tank"/>
 <tile id="185" type="tank"/>
 <tile id="186" type="tank"/>
 <tile id="187" type="tank"/>
 <tile id="188" type="tank"/>
 <tile id="189" type="tank"/>
 <tile id="190" type="tank"/>
 <tile id="200" type="tank"/>
 <tile id="201" type="tank"/>
 <tile id="202" type="tank"/>
 <tile id="203" type="tank"/>
 <tile id="204" type="tank"/>
 <tile id="205" type="tank"/>
 <tile id="206" type="tank"/>
 <tile id="207" type="tank"/>
 <tile id="208" type="tank"/>
 <tile id="209" type="tank"/>
 <tile id="210" type="tank"/>
 <tile id="211" type="tank"/>
 <tile id="212" type="tank"/>
 <tile id="213" type="tank"/>
 <tile id="214" type="tank"/>
 <tile id="215" type="tank"/>
 <tile id="225" type="tank"/>
 <tile id="226" type="tank"/>
 <tile id="227" type="tank"/>
 <tile id="228" type="tank"/>
 <tile id="229" type="tank"/>
 <tile id="230" type="tank"/>
 <tile id="231" type="tank"/>
 <tile id="232" type="tank"/>
 <tile id="233" type="tank"/>
 <tile id="234" type="tank"/>
 <tile id="235" type="tank"/>
 <tile id="236" type="tank"/>
 <tile id="237" type="tank"/>
 <tile id="238" type="tank"/>
 <tile id="239" type="tank"/>
 <tile id="240" type="tank"/>
 <tile id="242" type="6"/>
 <tile id="250" type="tank"/>
 <tile id="251" type="tank"/>
 <tile id="252" type="tank"/>
 <tile id="253" type="tank"/>
 <tile id="254" type="tank"/>
 <tile id="255" type="tank"/>
 <tile id="256" type="tank"/>
 <tile id="257" type="tank"/>
 <tile id="258" type="tank"/>
 <tile id="259" type="tank"/>
 <tile id="260" type="tank"/>
 <tile id="261" type="tank"/>
 <tile id="262" type="tank"/>
 <tile id="263" type="tank"/>
 <tile id="264" type="tank"/>
 <tile id="265" type="tank"/>
 <tile id="275" type="tank"/>
 <tile id="276" type="tank"/>
 <tile id="277" type="tank"/>
 <tile id="278" type="tank"/>
 <tile id="279" type="tank"/>
 <tile id="280" type="tank"/>
 <tile id="281" type="tank"/>
 <tile id="282" type="tank"/>
 <tile id="283" type="tank"/>
 <tile id="284" type="tank"/>
 <tile id="285" type="tank"/>
 <tile id="286" type="tank"/>
 <tile id="287" type="tank"/>
 <tile id="288" type="tank"/>
 <tile id="289" type="tank"/>
 <tile id="290" type="tank"/>
 <tile id="300" type="tank"/>
 <tile id="301" type="tank"/>
 <tile id="302" type="tank"/>
 <tile id="303" type="tank"/>
 <tile id="304" type="tank"/>
 <tile id="305" type="tank"/>
 <tile id="306" type="tank"/>
 <tile id="307" type="tank"/>
 <tile id="308" type="tank"/>
 <tile id="309" type="tank"/>
 <tile id="310" type="tank"/>
 <tile id="311" type="tank"/>
 <tile id="312" type="tank"/>
 <tile id="313" type="tank"/>
 <tile id="314" type="tank"/>
 <tile id="315" type="tank"/>
 <tile id="325" type="tank"/>
 <tile id="326" type="tank"/>
 <tile id="327" type="tank"/>
 <tile id="328" type="tank"/>
 <tile id="329" type="tank"/>
 <tile id="330" type="tank"/>
 <tile id="331" type="tank"/>
 <tile id="332" type="tank"/>
 <tile id="333" type="tank"/>
 <tile id="334" type="tank"/>
 <tile id="335" type="tank"/>
 <tile id="336" type="tank"/>
 <tile id="337" type="tank"/>
 <tile id="338" type="tank"/>
 <tile id="339" type="tank"/>
 <tile id="340" type="tank"/>
 <tile id="350" type="tank"/>
 <tile id="351" type="tank"/>
 <tile id="352" type="tank"/>
 <tile id="353" type="tank"/>
 <tile id="354" type="tank"/>
 <tile id="355" type="tank"/>
 <tile id="356" type="tank"/>
 <tile id="357" type="tank"/>
 <tile id="358" type="tank"/>
 <tile id="359" type="tank"/>
 <tile id="360" type="tank"/>
 <tile id="361" type="tank"/>
 <tile id="362" type="tank"/>
 <tile id="363" type="tank"/>
 <tile id="364" type="tank"/>
 <tile id="365" type="tank"/>
 <tile id="375" type="tank"/>
 <tile id="376" type="tank"/>
 <tile id="377" type="tank"/>
 <tile id="378" type="tank"/>
 <tile id="379" type="tank"/>
 <tile id="380" type="tank"/>
 <tile id="381" type="tank"/>
 <tile id="382" type="tank"/>
 <tile id="383" type="tank"/>
 <tile id="384" type="tank"/>
 <tile id="385" type="tank"/>
 <tile id="386" type="tank"/>
 <tile id="387" type="tank"/>
 <tile id="388" type="tank"/>
 <tile id="389" type="tank"/>
 <tile id="390" type="tank"/>
</tileset>
